<?php
    /**
     * ghtml_test.inc 实现对ghtml服务的单元测试；
     *
     * @copyright   2012-2013 Jtita soft foundation
     *              (http://www.jtita.com)
     * @author      Jtita team<jtita@outlook.com>
     * @license     http://www.apache.org/licenses/LICENSE-2.0.html
     *
     * @package     jtita.ghtmls
     * @version     1.0 beta
     *
     * @create      2013-04-08
     * @modify      2013-04-28
     */

    # 声明引用标志
    defined ('JTITA_GHTML', true);

    /**
     * 静态HTML生成类，提供对静态HTML的生成服务。
     *
     * @package jtita.ghtmls
     */
    abstract class Ghtml {

    }