<?php return array(
    'themes' => array(
        'default' => 'default',
        'member' => '__bootstrap',
        'admins' => 'default'
    ),
    'jtcore' => array(
        'visitor' => 'Y-m-d h:i'
    ),
    'globals' => array(
        'site' => array(
            'name' => 'Jtita 官方网站',
            'domain' => 'http://www.jtita.com\'s ”hdk ddd',
            'description' => 'Jtita 是一个完全免费的开源PHP架构，基于PHP 5.3+ 以上的版本，支持MVC、路由、缓存、事务、安全等诸多特性。',
            'seo' => 'Jtita php 框架a'
        ),

    ),
    'customs' => array()
);