<?php
    /**
     * smsg_notify_delivery.inc 声明短信通知服务对象;
     *
     * @copyright   2012-2013 Jtita soft foundation
     *              (http://www.jtita.com)
     * @author      Jtita team<jtita@outlook.com>
     * @license     http://www.apache.org/licenses/LICENSE-2.0.html
     *
     * @package     jtita.kernels.notifies.deliveries
     * @version     1.0 beta
     *
     * @create      2013-04-05
     * @modify      2013-04-28
     */

    /**
     * 短信通知投递类，提供通过邮件进行通知的能力。
     *
     * @package jtita.kernels.notifies.deliveries
     */
    class SmsgNotifyDelivery implements NotifyDelivery{
        public function deliver ($receiver, $message) {

        }
    }