<?php
    /**
     * XblVisitor.php 提供xblives的访问统计服务。
     *
     *  Copyright 2012 http://xbutu.com
     *
     * @package       xbutu/lives
     * @version       0.1
     *
     * @author        Zheng Guoping(http://weibo.com/zhenggp)
     * @create        2013-03-13
     * @modify        2013-03-13
     */

    /**
     * 访问者模型，提供访问者信息。
     */
    class XblVisitor extends ApplicationModel {

    }