<?php
    /**
     * accounts_controller.php 个人账户控制器。
     *
     * @copyright     2012-2013 Jtita soft foundation
     *                (http://www.jtita.com)
     * @author        Jtita team<jtita@outlook.com>
     * @license       http://www.jtita.com/license.txt
     *
     * @package     jtita.jtcore
     * @version     1.0 beta
     *
     * @create      2013-03-05
     * @modify      2013-04-15
     */

    /**
     * 账户控制器，提供当前管理员的相关信息管理服务。
     */
    class AccountsController extends AdminsController {
        /**
         * 默认行为
         */
        public function indexAction () {

        }

        /**
         * 资料行为
         */
        public function profileAction () {

        }

        /**
         * 修改密码
         */
        public function passwordAction () {

        }

    }