<?php
    /**
     * index_controller.inc 提供jtcore后台管理首页。
     *
     * @copyright     2012-2013 Jtita soft foundation
     *                (http://www.jtita.com)
     * @author        Jtita team<jtita@outlook.com>
     * @license       http://www.apache.org/licenses/LICENSE-2.0.html
     *
     * @package       jtita.jtcore
     * @version       1.0 beta
     *
     * @create        2012-10-25
     * @modify        2013-04-28
     */

    /**
     * jtcore 模块控制器，提供后台首页服务。
     *
     * @package jtita.jtcore
     */
    class IndexController extends AdminsController {

        /**
         * 首页动作。
         */
        public function indexAction () {

        }

        /**
         * 登陆动作。
         */
        public function signinAction () {

        }

        /**
         * 登出动作。
         */
        public function signoutAction () {

        }
    }