<?php
    /**
     * themes_tool_controller.php 声明网站主题管理控制器；
     *
     * @copyright   2012-2013 Jtita soft foundation
     *              (http://www.jtita.com)
     * @author      Jtita team<jtita@outlook.com>
     * @license     http://www.jtita.com/license.txt
     *
     * @package     jtita.jtcore
     * @version     1.0 beta
     *
     * @create      2012-01-29
     * @modify      2013-04-15
     */

    /**
     * 网站后台主题管理控制器。
     *
     * @package jtita.jtcore
     */
    class ThemesController extends AdminsController {

        /**
         * 默认活动；
         */
        public function indexAction () {

        }
    }