<?php
    /**
     *  objs.inc 全局动态行为配置文件。
     *
     * @copyright   2012-2013 Jtita soft foundation
     *              (http://www.jtita.com)
     * @author      Jtita team<jtita@outlook.com>
     * @license     http://www.jtita.com/license.txt
     *
     * @package     jtita.boots
     * @version     1.0 beta
     *
     * @create      2012-07-22
     * @modify      2013-04-07
     */

    /**
     * @example
     *      Jtita::behaviors('orders.services.order_service','submit',
     *      array('kernels.transactions.behaviors.autotrans_behavior' => array(),
     *            'kernels.logs.behaviors.autolog_behavior' => array(),
     *            'kernels.debuggers.behaviors.autobug_behavior' => array()));
     */

