<?php
    /**
     * autonotify_behavior.inc 提供自动通知服务;
     *
     * @copyright   2012-2013 Jtita soft foundation
     *              (http://www.jtita.com)
     * @author      Jtita team<jtita@outlook.com>
     * @license     http://www.apache.org/licenses/LICENSE-2.0.html
     *
     * @package     jtita.kernels.notifies.behaviors
     * @version     1.0 beta
     *
     * @create      2013-04-05
     * @modify      2013-04-28
     */

    /**
     * 邮件通知投递类，提供通过邮件进行通知的能力。
     *
     * @package jtita.kernels.notifies.behaviors
     */
    class AutonotifyBehavior extends AbstractBehavior{
        /**
         * @override AbstractBehavior::_invoke
         */
        protected function _invoke ($target, $args) {

        }

    }